<?php
/*
 * AUTOGENERATED CODE - DO NOT EDIT!
 *
 * This base class was generated by the Trellis library and
 * must not be modified manually. Any modifications to this
 * file will be lost upon triggering the next automatic
 * class generation.
 *
 * If you are looking for a place to alter the behaviour of
 * the 'DefaultToken' type please see the skeleton
 * class 'DefaultTokenType'. Modifications to the skeleton
 * file will prevail any subsequent class generation runs.
 *
 * To define new attributes or adjust existing attributes and their
 * default options modify the schema definition file of
 * the 'DefaultToken' type.
 *
 * @see https://github.com/honeybee/trellis
 */

namespace Foh\SystemAccount\User\Projection\Standard\Embed\Base;

use Honeybee\Projection\EmbeddedEntityType;
use Trellis\Common\Options;
use Trellis\Runtime\EntityTypeInterface;
use Trellis\Runtime\Attribute\AttributeInterface;

/**
 * Serves as the base class to the 'DefaultToken' type skeleton.
 */
abstract class DefaultTokenType extends EmbeddedEntityType
{
    /**
     * Creates a new 'DefaultTokenType' instance.
     */
    public function __construct(EntityTypeInterface $parent = null, AttributeInterface $parent_attribute = null)
    {
        parent::__construct(
            'DefaultToken',
            [
                new \Trellis\Runtime\Attribute\Text\TextAttribute(
                    'token',
                    $this,
                    [],
                    $parent_attribute
                ),
                new \Trellis\Runtime\Attribute\Timestamp\TimestampAttribute(
                    'expires_at',
                    $this,
                    [],
                    $parent_attribute
                ),
            ],
            new Options(
                []
            ),
            $parent,
            $parent_attribute
        );
    }

    /**
     * Returns the EntityInterface implementor to use when creating new entities.
     *
     * @return string Fully qualified name of an EntityInterface implementation.
     */
    public static function getEntityImplementor()
    {
        return '\\Foh\\SystemAccount\\User\\Projection\\Standard\\Embed\\DefaultToken';
    }
}
